server:
  port: 19008
spring:
  application:
    name: awzsu-sms
  rabbitmq:
    host: 192.168.25.90
aliyun:
  sms:
    accessKeyId: **************
    accessKeySecret: **************
    sign_name: **************
    template_code: **************
